# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secu', '0002_auto_20160427_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
