# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('hashed_password', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=200)),
                ('profile', models.CharField(max_length=100)),
                ('bitbars', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(verbose_name='Date Updated')),
            ],
        ),
    ]
